services:
  - type: web
    name: tg_card_bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python tg_card.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
